version: '3.7'
services:
  db:
    image: postgres:9.4
    ports:
      - "5432:5432"
    volumes:
#      - "./data/db:/var/lib/postgresql/data"
       - "./init/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_DB=unittesting
      - POSTGRES_USER=julien
      - POSTGRES_PASSWORD=myerp
      
